/**
 * test_mimi_encoder.cpp
 *
 * Validates the C++ Mimi encoder by comparing its output codes against
 * Python-generated reference codes (from scripts/validate_mimi_encoder.py).
 *
 * Usage:
 *   test_mimi_encoder [options]
 *
 * Options:
 *   --tokenizer <path>   Path to tokenizer GGUF (must contain mimi_enc.* tensors)
 *   --audio <path>       Input audio WAV file (float32 or PCM, 24 kHz mono)
 *   --ref-codes <path>   Reference codes binary [n_frames * n_codebooks * int32]
 *                        (generated by scripts/validate_mimi_encoder.py)
 *   --codes-out <path>   Write C++ output codes to this path for external comparison
 *   --n-codebooks <n>    Expected number of codebooks (default: 16)
 *   --threshold <f>      Minimum match rate to PASS (default: 0.95)
 *
 * If --ref-codes is provided: encodes audio, compares against reference, prints report.
 * If --codes-out is provided: also writes the C++ codes to that file.
 * If neither: just encodes and prints frame count (smoke test).
 */

#include "mimi_encoder.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cassert>
#include <fstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
#include <numeric>

// ============================================================
// WAV loader (mono float32, supports PCM-16 and PCM float32)
// ============================================================
static bool load_wav(const std::string & path,
                     std::vector<float> & samples,
                     int & sample_rate) {
    FILE * f = fopen(path.c_str(), "rb");
    if (!f) { fprintf(stderr, "Cannot open: %s\n", path.c_str()); return false; }

    auto rd4 = [&](uint32_t & v) { return fread(&v, 4, 1, f) == 1; };
    auto rd2 = [&](uint16_t & v) { return fread(&v, 2, 1, f) == 1; };

    char riff[4], wave[4];
    uint32_t file_size;
    if (fread(riff, 1, 4, f) != 4 || strncmp(riff, "RIFF", 4)) { fclose(f); return false; }
    if (!rd4(file_size)) { fclose(f); return false; }
    if (fread(wave, 1, 4, f) != 4 || strncmp(wave, "WAVE", 4)) { fclose(f); return false; }

    uint16_t fmt = 0, nch = 0, bps = 0;
    uint32_t sr = 0;
    while (!feof(f)) {
        char cid[4]; uint32_t csz;
        if (fread(cid, 1, 4, f) != 4) break;
        if (!rd4(csz)) break;
        if (!strncmp(cid, "fmt ", 4)) {
            if (!rd2(fmt) || !rd2(nch)) break;
            if (!rd4(sr)) break;
            fseek(f, 6, SEEK_CUR);
            if (!rd2(bps)) break;
            if (csz > 16) fseek(f, (long)(csz - 16), SEEK_CUR);
        } else if (!strncmp(cid, "data", 4)) {
            sample_rate = (int)sr;
            if (fmt == 1 && bps == 16) {
                int n = (int)(csz / (2 * nch));
                std::vector<int16_t> raw(n * nch);
                fread(raw.data(), 2, n * nch, f);
                samples.resize(n);
                for (int i = 0; i < n; ++i) {
                    float s = 0;
                    for (int c = 0; c < nch; ++c) s += raw[i*nch+c] / 32768.0f;
                    samples[i] = s / nch;
                }
            } else if (fmt == 3 && bps == 32) {
                int n = (int)(csz / (4 * nch));
                std::vector<float> raw(n * nch);
                fread(raw.data(), 4, n * nch, f);
                samples.resize(n);
                for (int i = 0; i < n; ++i) {
                    float s = 0;
                    for (int c = 0; c < nch; ++c) s += raw[i*nch+c];
                    samples[i] = s / nch;
                }
            } else {
                fprintf(stderr, "Unsupported WAV: fmt=%d bps=%d\n", fmt, bps);
                fclose(f); return false;
            }
            fclose(f); return true;
        } else {
            fseek(f, (long)csz, SEEK_CUR);
        }
    }
    fclose(f); return false;
}

// Also load raw float32 audio binary (from validate_mimi_encoder.py --save-audio)
static bool load_raw_f32(const std::string & path, std::vector<float> & samples) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f.is_open()) return false;
    size_t sz = f.tellg();
    f.seekg(0);
    samples.resize(sz / sizeof(float));
    f.read(reinterpret_cast<char*>(samples.data()), sz);
    return f.good();
}

// Resample from src_rate to 24000 using linear interpolation
static void resample_linear(const std::vector<float> & in, int src_rate,
                             std::vector<float> & out) {
    if (src_rate == 24000) { out = in; return; }
    double ratio = (double)src_rate / 24000.0;
    int n_out = (int)((double)in.size() / ratio);
    out.resize(n_out);
    for (int i = 0; i < n_out; ++i) {
        double src = i * ratio;
        int i0 = (int)src, i1 = i0 + 1;
        double f = src - i0;
        if (i1 >= (int)in.size()) out[i] = in.back();
        else out[i] = (float)((1.0-f)*in[i0] + f*in[i1]);
    }
}

// ============================================================
// Binary I/O
// ============================================================
static bool load_int32_bin(const std::string & path, std::vector<int32_t> & data) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f.is_open()) return false;
    size_t sz = f.tellg(); f.seekg(0);
    data.resize(sz / sizeof(int32_t));
    f.read(reinterpret_cast<char*>(data.data()), sz);
    return f.good();
}

static bool save_int32_bin(const std::string & path, const std::vector<int32_t> & data) {
    std::ofstream f(path, std::ios::binary);
    if (!f.is_open()) return false;
    f.write(reinterpret_cast<const char*>(data.data()),
            data.size() * sizeof(int32_t));
    return f.good();
}

// ============================================================
// Comparison
// ============================================================
struct CompareResult {
    int n_frames = 0;
    int n_q      = 0;
    bool exact   = false;
    float match_rate = 0.0f;
    int first_mismatch = -1;
    std::vector<float> per_cb_match;
};

static CompareResult compare_codes(const std::vector<int32_t> & cpp_codes,
                                    const std::vector<int32_t> & ref_codes,
                                    int n_q) {
    CompareResult r;
    if (cpp_codes.empty() || ref_codes.empty()) return r;

    int n_cpp = (int)cpp_codes.size() / n_q;
    int n_ref = (int)ref_codes.size()  / n_q;
    int n_cmp = std::min(n_cpp, n_ref);

    r.n_frames = n_cmp;
    r.n_q      = n_q;
    r.per_cb_match.resize(n_q, 0.0f);

    int total_match = 0;
    for (int f = 0; f < n_cmp; ++f) {
        bool frame_ok = true;
        for (int q = 0; q < n_q; ++q) {
            if (cpp_codes[f*n_q+q] == ref_codes[f*n_q+q]) {
                r.per_cb_match[q] += 1.0f;
                total_match++;
            } else {
                frame_ok = false;
            }
        }
        if (!frame_ok && r.first_mismatch < 0) r.first_mismatch = f;
    }
    for (int q = 0; q < n_q; ++q)
        r.per_cb_match[q] /= (float)std::max(1, n_cmp);

    r.match_rate = (float)total_match / (float)std::max(1, n_cmp * n_q);
    r.exact = (total_match == n_cmp * n_q && n_cpp == n_ref);
    return r;
}

// ============================================================
// Usage
// ============================================================
static void print_usage(const char * prog) {
    fprintf(stderr,
        "Usage: %s [options]\n"
        "Options:\n"
        "  --tokenizer <path>    Tokenizer GGUF with mimi_enc.* tensors\n"
        "  --audio <path>        Input WAV or raw float32 binary (24 kHz mono)\n"
        "  --ref-codes <path>    Reference int32 codes from validate_mimi_encoder.py\n"
        "  --codes-out <path>    Write C++ codes to file\n"
        "  --n-codebooks <n>     Expected codebooks (default: 16)\n"
        "  --threshold <f>       Pass threshold 0..1 (default: 0.95)\n"
        "\n"
        "Steps to use:\n"
        "  1. python scripts/validate_mimi_encoder.py --audio audio.mp3 \\\n"
        "         --tokenizer-dir models/Qwen3-TTS-Tokenizer-12Hz\n"
        "     (saves reference/mimi_enc_py_codes.bin)\n"
        "  2. test_mimi_encoder --tokenizer models/qwen3-tts-tokenizer-f16.gguf \\\n"
        "         --audio reference/mimi_enc_test_audio.bin \\\n"
        "         --ref-codes reference/mimi_enc_py_codes.bin\n",
        prog);
}

// ============================================================
// Main
// ============================================================
int main(int argc, char ** argv) {
    std::string tokenizer_path = "models/qwen3-tts-tokenizer-f16.gguf";
    std::string audio_path;
    std::string ref_codes_path;
    std::string codes_out_path;
    int  n_codebooks = 16;
    float threshold  = 0.95f;

    for (int i = 1; i < argc; ++i) {
        if (!strcmp(argv[i], "--tokenizer") && i+1 < argc) {
            tokenizer_path = argv[++i];
        } else if (!strcmp(argv[i], "--audio") && i+1 < argc) {
            audio_path = argv[++i];
        } else if (!strcmp(argv[i], "--ref-codes") && i+1 < argc) {
            ref_codes_path = argv[++i];
        } else if (!strcmp(argv[i], "--codes-out") && i+1 < argc) {
            codes_out_path = argv[++i];
        } else if (!strcmp(argv[i], "--n-codebooks") && i+1 < argc) {
            n_codebooks = atoi(argv[++i]);
        } else if (!strcmp(argv[i], "--threshold") && i+1 < argc) {
            threshold = (float)atof(argv[++i]);
        } else if (!strcmp(argv[i], "--help")) {
            print_usage(argv[0]); return 0;
        }
    }

    if (audio_path.empty()) {
        // Try default paths
        for (const char * p : {"reference/mimi_enc_test_audio.bin", "clone.wav", "audio.wav"}) {
            std::ifstream t(p); if (t.good()) { audio_path = p; break; }
        }
    }
    if (audio_path.empty()) {
        fprintf(stderr, "ERROR: No audio file specified and no default found.\n");
        print_usage(argv[0]); return 1;
    }

    fprintf(stderr, "=== Mimi Encoder Validation Test ===\n\n");

    // ---- Step 1: Load audio -------------------------------------------
    fprintf(stderr, "Loading audio: %s\n", audio_path.c_str());
    std::vector<float> samples;
    int sample_rate = 24000;

    // Detect file type by extension
    bool is_raw = (audio_path.size() > 4 &&
                   audio_path.substr(audio_path.size()-4) == ".bin");
    if (is_raw) {
        if (!load_raw_f32(audio_path, samples)) {
            fprintf(stderr, "ERROR: Cannot load raw audio binary: %s\n", audio_path.c_str());
            return 1;
        }
        fprintf(stderr, "  Loaded %zu float32 samples (raw binary)\n", samples.size());
    } else {
        if (!load_wav(audio_path, samples, sample_rate)) {
            fprintf(stderr, "ERROR: Cannot load WAV: %s\n", audio_path.c_str());
            return 1;
        }
        fprintf(stderr, "  Loaded %zu samples @ %d Hz\n", samples.size(), sample_rate);
        if (sample_rate != 24000) {
            fprintf(stderr, "  Resampling %d -> 24000 Hz...\n", sample_rate);
            std::vector<float> resampled;
            resample_linear(samples, sample_rate, resampled);
            samples = std::move(resampled);
            sample_rate = 24000;
        }
    }

    // ---- Step 2: Load Mimi encoder -----------------------------------
    fprintf(stderr, "\nLoading Mimi encoder: %s\n", tokenizer_path.c_str());
    qwen3_tts::MimiEncoder encoder;
    if (!encoder.load_model(tokenizer_path)) {
        fprintf(stderr, "ERROR: %s\n", encoder.get_error().c_str());
        fprintf(stderr, "\nNOTE: If this says 'No Mimi encoder tensors found', you need to\n");
        fprintf(stderr, "re-convert the tokenizer GGUF with the updated converter:\n");
        fprintf(stderr, "  python scripts/convert_tokenizer_to_gguf.py \\\n");
        fprintf(stderr, "      --input models/Qwen3-TTS-Tokenizer-12Hz \\\n");
        fprintf(stderr, "      --output models/qwen3-tts-tokenizer-f16.gguf --type f16\n");
        return 1;
    }
    fprintf(stderr, "  Encoder loaded: num_valid_quantizers=%d\n",
            encoder.get_config().num_valid_quantizers);

    n_codebooks = encoder.get_config().num_valid_quantizers;

    // ---- Step 3: Encode audio ----------------------------------------
    fprintf(stderr, "\nEncoding %zu samples...\n", samples.size());
    std::vector<int32_t> cpp_codes;
    int32_t n_frames = 0;

    if (!encoder.encode(samples.data(), (int32_t)samples.size(), cpp_codes, n_frames)) {
        fprintf(stderr, "ERROR: encode() failed: %s\n", encoder.get_error().c_str());
        return 1;
    }
    fprintf(stderr, "  Encoded: %d frames x %d codebooks = %zu codes\n",
            n_frames, n_codebooks, cpp_codes.size());

    // ---- Step 4: Save codes if requested -----------------------------
    if (!codes_out_path.empty()) {
        if (!save_int32_bin(codes_out_path, cpp_codes)) {
            fprintf(stderr, "WARNING: Failed to save codes to %s\n", codes_out_path.c_str());
        } else {
            fprintf(stderr, "\nCodes saved to: %s (%zu int32 values)\n",
                    codes_out_path.c_str(), cpp_codes.size());
        }
    }

    // ---- Step 5: Compare against reference ---------------------------
    if (ref_codes_path.empty()) {
        // No reference — smoke test only
        fprintf(stderr, "\n=== SMOKE TEST PASS ===\n");
        fprintf(stderr, "Encoded %d frames. No reference provided for comparison.\n", n_frames);
        fprintf(stderr, "Run scripts/validate_mimi_encoder.py first to generate reference codes.\n");
        return 0;
    }

    fprintf(stderr, "\nLoading reference codes: %s\n", ref_codes_path.c_str());
    std::vector<int32_t> ref_codes;
    if (!load_int32_bin(ref_codes_path, ref_codes)) {
        fprintf(stderr, "ERROR: Cannot load reference codes: %s\n", ref_codes_path.c_str());
        return 1;
    }
    int ref_frames = (int)ref_codes.size() / n_codebooks;
    fprintf(stderr, "  Reference: %d frames x %d codebooks\n", ref_frames, n_codebooks);

    // ---- Step 6: Report -----------------------------------------------
    CompareResult r = compare_codes(cpp_codes, ref_codes, n_codebooks);

    fprintf(stderr, "\n");
    fprintf(stderr, "=== Mimi Encoder Comparison Report ===\n");
    fprintf(stderr, "Frames compared:    %d\n", r.n_frames);
    fprintf(stderr, "Overall match rate: %.2f%%\n", r.match_rate * 100.0f);
    fprintf(stderr, "Exact match:        %s\n", r.exact ? "YES" : "NO");
    if (r.first_mismatch >= 0)
        fprintf(stderr, "First mismatch:     frame %d\n", r.first_mismatch);

    fprintf(stderr, "\nPer-codebook match rates:\n");
    for (int q = 0; q < n_codebooks; ++q) {
        float pct = r.per_cb_match[q] * 100.0f;
        int bar = (int)(pct / 5.0f);
        fprintf(stderr, "  CB%2d: %6.1f%%  [", q, pct);
        for (int b = 0; b < 20; ++b) fprintf(stderr, "%c", b < bar ? '#' : '.');
        fprintf(stderr, "]\n");
    }

    // Print first few frames comparison
    int show_frames = std::min(3, r.n_frames);
    if (show_frames > 0 && r.first_mismatch >= 0) {
        fprintf(stderr, "\nFirst %d frames comparison (C++ | Python):\n", show_frames);
        for (int f = 0; f < show_frames; ++f) {
            fprintf(stderr, "  Frame %d: ", f);
            for (int q = 0; q < n_codebooks; ++q) {
                int cv = cpp_codes[f*n_codebooks+q];
                int rv = ref_codes[f*n_codebooks+q];
                fprintf(stderr, cv == rv ? "%d " : "[%d!=%d] ", cv, rv);
            }
            fprintf(stderr, "\n");
        }
    }

    fprintf(stderr, "\n");
    fprintf(stderr, "===========================================\n");
    if (r.exact) {
        fprintf(stderr, "RESULT: PASS (exact match)\n");
    } else if (r.match_rate >= threshold) {
        fprintf(stderr, "RESULT: PASS (%.1f%% >= %.0f%% threshold)\n",
                r.match_rate * 100.0f, threshold * 100.0f);
    } else {
        fprintf(stderr, "RESULT: FAIL (%.1f%% < %.0f%% threshold)\n",
                r.match_rate * 100.0f, threshold * 100.0f);
        fprintf(stderr, "===========================================\n");
        return 1;
    }
    fprintf(stderr, "===========================================\n");
    return 0;
}
